booxmedialtd/api-documentation

legacy/snippets/channel/Channel.yml

Ticket: https://jira.aminocom.com/browse/BPLAT-10757
semver: +minor

phi/BPLAT-10757: [WS] Add Pause Live TV flag to CMS and channel v2

---

rest/snippets/EnrichedMetadata/ProgramEntity.yml

https://jira.aminocom.com/browse/BPLAT-10812

BPLAT-10812: Updating programs api specs

---

rest/endpoints/media/media_playback_sessions.yaml

https://jira.aminocom.com/browse/BPLAT-10206

BPLAT-10206: Remove user_id from API documentation where it's not applicable

---

rest/endpoints/user_recordings/user_recordings.yml

https://jira.aminocom.com/browse/BPLAT-11136

BPLAT-11136: Adding missing service parameter to user recordings API

---

legacy/endpoints/login/login.yml

https://jira.aminocom.com/browse/BPLAT-11057

BPLAT-11057: Add access and refresh token to login action example response.

---

rest/endpoints/user_configuration/favourite_channels.yml

Ticket: https://jira.aminocom.com/browse/BPLAT-7801
semver: +minor

Phi/BPLAT-7801: [WS] GET /users/{user_id}/favourite_channel_lists

---

legacy/endpoints/login/login.yml

Ticket: https://jira.aminocom.com/browse/BPLAT-11058
`semver: +minor`

phi/BPLAT-11058: [WS] Client guidelines for cookie-token exchange

---

rest/snippets/UserConfiguration/UserChannelLockingConfiguration.yml

https://jira.aminocom.com/browse/BPLAT-10996

BPLAT-10996 add lock_adult_channels

---

rest/endpoints/user_configuration/user_info.yml
rest/snippets/Config/UserEntity.yml
rest/snippets/UserConfiguration/UserChannelLockingConfiguration.yml

https://jira.aminocom.com/browse/BPLAT-10994
- update patch user info "Available since"

BPLAT-10994 change user pin from int to string

---

rest/snippets/Config/UserEntity.yml

https://jira.aminocom.com/browse/BPLAT-11022
semver: +minor

phi/BPLAT-11022: [WS] User API to indicate that PIN is in default state

---

rest/endpoints/media/media_playback_sessions.yaml

https://jira.aminocom.com/browse/BPLAT-11252

BPLAT-11252: Add documentation for PUT

---

rest/endpoints/user_configuration/locked_channels.yml

https://jira.aminocom.com/browse/BPLAT-10999

BPLAT-10999 update available since

---

legacy/endpoints/user_management_bss/user_management.yml

https://jira.aminocom.com/browse/BPLAT-10993
`semver: +minor`

phi/BPLAT-10993: Add another param to legacy management Put API

---

rest/endpoints/user_configuration/locked_channels.yml

https://jira.aminocom.com/browse/BPLAT-11000
`semver: +minor`

phi/BPLAT-11000: Update API spec for PATCH Channel Lock API

---

rest/endpoints/media/recording_playable_stream.yml
rest/snippets/Media/StreamEntity.yml

Ticket: https://jira.aminocom.com/browse/BPLAT-11167
semver: +minor

phi/BPLAT-11167: New request param and response attribute for recording stream api

---

rest/endpoints/user_configuration/locked_channels.yml

https://jira.aminocom.com/browse/BPLAT-11429

BPLAT-11429: Update channel lock specs

---

rest/endpoints/media/recording_playable_stream.yml
rest/snippets/Media/StreamEntity.yml

https://jira.aminocom.com/browse/BPLAT-11169
Note: use hide whitespace to view the changes.

[WS] BPLAT-11169 Add new query param and links property to recording playable stream api documentation

---

rest/endpoints/media/recording_playable_stream.yml

Fixed an issue with wrong formatting

[WS] BPLAT-11169 Fix broken API page

---

rest/endpoints/media/recording_playable_stream.yml
rest/snippets/Media/StreamEntity.yml

Move links block to recording_playable_stream.yml instead of StreamEntity

[WS] BPLAT-11169 Fix Missing links

---

rest/endpoints/media/live_playable_stream.yml

https://jira.aminocom.com/browse/BPLAT-11182

BPLAT-11181: Update channel live streams endpoint with 451 response

---

rest/endpoints/media/recording_playable_stream.yml

https://jira.aminocom.com/browse/BPLAT-11182

[WS] BPLAT-11182 Update recording streams API Doc with new Response code

---

rest/snippets/UserRecordings/UserRecordingEntity.yml

- Removed "auto_delete" from recordings, it belongs to recording requests later
- Removed "recording location", that feature is dropped
- Moved "automated_maintenance" properties on top -- this is how they are returned
https://jira.aminocom.com/browse/BPLAT-10673

BPLAT-10673 Updating API specs to reflect reality

---

rest/snippets/Auth/UserSession.yml
rest/snippets/UserConfiguration/UserProfile.yml

https://jira.aminocom.com/browse/BPLAT-11696

[WS] BPLAT-11696 Update User Profiles API specs to include age limit

---

rest/endpoints/user_configuration/favourite_channels.yml

https://jira.aminocom.com/browse/BPLAT-11816

Phi/BPLAT-11816: Modify doc since

---

rest/snippets/UserRecordings/RecordingGroupEntity.yml

Relationships have to be at the same level as Attributes.
https://jira.aminocom.com/browse/BPLAT-10671

BPLAT-10671 re-add relationships at the correct level

---

rest/endpoints/user_configuration/user_profiles.yml
rest/snippets/UserConfiguration/UserProfile.yml

https://jira.aminocom.com/browse/BPLAT-11708

[WS] BPLAT-11708 Update UserProfiles: rename nickname and add links

---

rest/endpoints/user_configuration/user_profiles.yml
rest/snippets/UserConfiguration/UserProfilePatchRequestBody.yml

https://jira.aminocom.com/browse/BPLAT-11710
`semver: +minor`

phi/BPLAT-11710: Modify spec api

---

rest/endpoints/user_configuration/user_profiles.yml

https://jira.aminocom.com/browse/BPLAT-11710
semver: +minor

phi/BPLAT-11710: Modify the schema

---

rest/endpoints/user_configuration/user_profiles.yml

https://jira.aminocom.com/browse/BPLAT-11708

[WS] BPLAT-11708 Update available since for GET and POST endpoints spec

---

rest/endpoints/user_configuration/user_profiles.yml
rest/snippets/Auth/AuthenticationTokens.yml

https://jira.aminocom.com/browse/BPLAT-11719

BPLAT-11719 add extra information to user profile authentiction

---

rest/snippets/Auth/AuthenticationTokens.yml

https://jira.aminocom.com/browse/BPLAT-11719

BPLAT-11719 rename object to match the correct name

---

rest/endpoints/user_configuration/user_profiles.yml
rest/snippets/UserConfiguration/UserProfile.yml

https://jira.aminocom.com/browse/BPLAT-11708

[WS] BPLAT-11708 Update missing links from the userprofile spec

---

rest/snippets/Auth/AuthenticationTokens.yml

https://jira.aminocom.com/browse/BPLAT-11719

BPLAT-11719 rename expires -> expires_at

---

rest/endpoints/auth/authentication.yml

https://jira.aminocom.com/browse/BPLAT-11893

BPLAT-11893 Update authentication api spec to contain grant_type

---

rest/endpoints/auth/authentication.yml

https://jira.aminocom.com/browse/BPLAT-11893

BPLAT-11893 Fix broken doc with wrong indentations

---

rest/endpoints/auth/authentication.yml

https://jira.aminocom.com/browse/BPLAT-11893

BPLAT-11893 Update API spec to be consistent with the AuthenticationTokensResource

---

rest/endpoints/auth/authentication.yml

https://jira.aminocom.com/browse/BPLAT-11893

BPLAT-11893 Hide delete access_token endpoint

---

rest/endpoints/user_configuration/user_profiles.yml

https://jira.aminocom.com/browse/BPLAT-11710
semver: +minor

phi/BPLAT-11710: Update available since for Patch User profile api

---

rest/endpoints/catchup/catchup.yml
rest/endpoints/enriched_metadata/channels.yml
rest/endpoints/enriched_metadata/credited_persons.yml
rest/endpoints/enriched_metadata/genres.yml
rest/endpoints/enriched_metadata/programs.yml
rest/endpoints/enriched_metadata/seasons.yml
rest/endpoints/enriched_metadata/series.yml
rest/endpoints/schedule/broadcast_slots.yml
rest/endpoints/subscription/subscriptions.yml
rest/endpoints/user_recordings/user_recordings.yml

https://jira.aminocom.com/browse/BPLAT-11984

Remove Accept-Language TODO from API documentation

---

rest/endpoints/user_configuration/user_profiles.yml

https://jira.aminocom.com/browse/BPLAT-11711

BPLAT-11711 Update available since user profile token

---

rest/endpoints/user_configuration/favourite_channels.yml

https://jira.aminocom.com/browse/BPLAT-11889

BPLAT-11889: Change PUT to PATCH for favourite channel list

---

rest/endpoints/user_configuration/favourite_channels.yml

https://jira.aminocom.com/browse/BPLAT-11888

BPLAT-11888 Update profile based favourite channel list endpoints

---

rest/endpoints/user_configuration/favourite_channels.yml

https://jira.aminocom.com/browse/BPLAT-11888

BPLAT-11888 Minor update profile based favourite channel list endpoints

---

rest/snippets/UserConfiguration/UserProfile.yml

https://jira.aminocom.com/browse/BPLAT-12005

BPLAT-12005 Added is_default to UserProfile

---

rest/snippets/UserConfiguration/UserProfilePatchRequestBody.yml

https://jira.aminocom.com/browse/BPLAT-12005

BPLAT-12005 Fix documentation for PATCH

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12048

BPLAT-12048 Updated endpoint documentation.

---

rest/endpoints/enriched_metadata/programs.yml

https://jira.aminocom.com/browse/BPLAT-12106

Phi/BPLAT-12106: Remove unnecessary parameter.

---

rest/endpoints/enriched_metadata/programs.yml

https://jira.aminocom.com/browse/BPLAT-12106

Phi/BPLAT-12106: Modify spec

---

rest/endpoints/enriched_metadata/programs.yml

https://jira.aminocom.com/browse/BPLAT-12108

phi/BPLAT-12108: Do not support filter by program.title and description ow but later

---

rest/endpoints/user_recordings/profile_recordings.yml

This seems to be the most likely description of the language parameter, although I have not verified it.

BPLAT-12048 Update documentation for language parameter

---

legacy/snippets/epg/EPGitem.yml

https://jira.aminocom.com/browse/BPLAT-4302

BPLAT-4302 add series_id to EPGitem for EPGv3

---

rest/snippets/Auth/AuthenticationTokens.yml

https://jira.aminocom.com/browse/BPLAT-12164

BPLAT-12164 user_id must always be output as string type

---

rest/snippets/UserConfiguration/UserProfile.yml

https://jira.aminocom.com/browse/BPLAT-12164

Bart.BPLAT-12164.user id must always be string type

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-10674

BPLAT-10674 Update documentation for grouped recordings endpoint

---

rest/endpoints/user_recordings/profile_recordings.yml
rest/snippets/General/JsonApiErrorEntity.yml
rest/snippets/UserRecordings/RecordingEntity.yml

https://jira.aminocom.com/browse/BPLAT-12079

BPLAT-12079: Add API spec for create recording API

---

rest/endpoints/auth/authentication.yml
rest/endpoints/user_configuration/user_profiles.yml

https://jira.aminocom.com/browse/BPLAT-12260
@booxmedialtd/ws-merger

BPLAT-12260: Remove obsolete endpoint

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12081

BPLAT-12260: Update spec for delete profile recording endpoint

---

rest/snippets/UserRecordings/RecordingGroupEntity.yml

https://jira.aminocom.com/browse/BPLAT-12083

[WS] BPLAT-12083 Remove last_recording_watched and duration_seconds from groups

---

rest/endpoints/user_recordings/profile_recordings.yml
rest/snippets/UserRecordings/RecordingEntity.yml

https://jira.aminocom.com/browse/BPLAT-12080

BPLAT-12080 patch Recording

---

rest/endpoints/user_recordings/profile_recordings.yml
rest/snippets/Epg/BroadcastSlotEntity.yml
rest/snippets/UserRecordings/RecordingEntity.yml

Refactored recording entity structure.
Added broadcast slot entity
https://jira.aminocom.com/browse/BPLAT-12330

BPLAT-12330: Update response for get grouped recordings.

---

rest/endpoints/user_recordings/profile_recordings.yml
rest/snippets/UserRecordings/RecordingGroupEntity.yml

https://jira.aminocom.com/browse/BPLAT-12083

BPLAT-12083: include series in response as "included"

---

rest/endpoints/user_recordings/profile_recordings.yml
rest/snippets/UserRecordings/RecordingEntity.yml

https://jira.aminocom.com/browse/BPLAT-12084

phi/BPLAT-12084: Update Api spec

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12079

BPLAT-12079: Add error response for case when trying to create existing recording

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12084

Phi/BPLAT-12084: Update Available Since

---

rest/endpoints/user_recordings/profile_recordings.yml
rest/snippets/UserRecordings/BatchDeleteRequestEntity.yml

https://jira.aminocom.com/browse/BPLAT-12082

BPLAT-12082 batch delete Recording

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12082
Fixed error in reference to request bodyand fixed example of 404 which had the wrong error code and wrong details.

BPLAT-12082 Fixed errors

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12400

[WS] BPLAT-12400 Api spec for recorded broadcast slots

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12400

Modify tag to place it under correct block

---

rest/endpoints/user_recordings/profile_recordings.yml
rest/snippets/UserRecordings/StorageQuotaEntity.yml
rest/snippets/UserRecordings/UserRecordingsQuotaEntity.yml

https://jira.aminocom.com/browse/BPLAT-12326

[WS] BPLAT-12326 API doc for GET Available recording space

---

rest/endpoints/playback_info/playback_info.yml
rest/snippets/PlaybackInfo/PlaybackInfoEntity.yml

https://jira.aminocom.com/browse/BPLAT-12230

BPLAT-12230: Add GET playback info API spec

---

rest/endpoints/playback_info/playback_info.yml

https://jira.aminocom.com/browse/BPLAT-12231

[WS] BPLAT-12231 API doc for PlaybackInfo Index

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12421

BPLAT-12421: Add filter param for is_favourite recordings

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12323

BPLAT-12323: Api specs for most popular endpoint.

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12421

BPLAT-12421: Add filter param for is_favourite recordings to ungrouped endpoint too

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12421

BPLAT-12421: Add filter param for is_favourite recordings to recordings by group endpoint

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12427

[WS] BPLAT-12427 Update Recording Search Endpoint

---

rest/endpoints/auth/authentication.yml

https://jira.aminocom.com/browse/BPLAT-12506

BPLAT-12506: added password authentication spec description

---

rest/endpoints/user_configuration/user_preferences.yml
rest/snippets/UserConfiguration/UserEntity.yml

https://jira.aminocom.com/browse/BPLAT-12511

BPLAT-12511: Add spec for user preferences API v2

---

rest/endpoints/user_recordings/profile_recordings.yml
rest/snippets/UserRecordings/AutoRecordingRequestEntity.yml

https://jira.aminocom.com/browse/BPLAT-12072
preview https://confluence.aminocom.com/display/BPLAT/%5BWIP+-+Garrick%5D+API+draft#/Automated%20Recording%20Requests/indexRecordingRequests

BPLAT-12072 Add get auto recording requests

---

rest/snippets/UserRecordings/AutoRecordingRequestEntity.yml
rest/snippets/UserRecordings/RecordingGroupEntity.yml

https://jira.aminocom.com/browse/BPLAT-12072
preview https://confluence.aminocom.com/display/BPLAT/%5BWIP+-+Garrick%5D+API+draft#/Automated%20Recording%20Requests/indexRecordingRequests

BPLAT-12072 review changes

---

rest/endpoints/auth/authentication.yml

Fixed 'Available since' description for refreshTokenGrantType
https://jira.aminocom.com/browse/BPLAT-12506

BPLAT-12506: Available since fix

---

rest/endpoints/enriched_metadata/series.yml

https://jira.aminocom.com/browse/BPLAT-12686

BPLAT-12686 Updated filter spec for series

---

rest/endpoints/user_recordings/profile_recordings.yml
rest/snippets/UserRecordings/AutoRecordingRequestEntity.yml

https://jira.aminocom.com/browse/BPLAT-12075
preview: https://confluence.aminocom.com/pages/viewpage.action?spaceKey=BPLAT&title=%5BWIP+-+Garrick%5D+API+draft#/Automated%20Recording%20Requests/updateRecordingRequests

BPLAT-12075 Patch recording request

---

rest/endpoints/user_configuration/user_preferences.yml

https://jira.aminocom.com/browse/BPLAT-12525

BPLAT-12525: Add spec for request password reset endpoint.

---

rest/endpoints/user_recordings/profile_recordings.yml
rest/snippets/UserRecordings/AutoRecordingRequestEntity.yml

The ticket is: https://jira.aminocom.com/browse/BPLAT-12073

BPLAT-12073: added createRecordingRequest POST endpoind spec

---

rest/endpoints/media/live_playable_stream.yml
rest/endpoints/media/recording_playable_stream.yml

https://jira.aminocom.com/browse/BPLAT-12839

BPLAT-12839: Fix fail base path

---

rest/endpoints/user_configuration/user_preferences.yml

https://jira.aminocom.com/browse/BPLAT-12526

BPLAT-12526 add spec for confirm_reset_password

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12074

BPLAT-12074: DELETE recording request

---

rest/snippets/UserRecordings/AutoRecordingRequestEntity.yml

https://jira.aminocom.com/browse/BPLAT-12882
Update API spec to match release answer.

BPLAT-12882: fix API specs

---

rest/snippets/Config/UserEntity.yml

https://jira.aminocom.com/browse/BPLAT-12626

BPLAT-12626 Add user_flags in UserEntity api doc definition

---

rest/snippets/Config/UserEntity.yml

https://jira.aminocom.com/browse/BPLAT-12626

BPLAT-12626 Review fixes

---

rest/snippets/Config/UserEntity.yml

https://jira.aminocom.com/browse/BPLAT-12626

BPLAT-12626 Fix api example for user_flags property

---

rest/snippets/Auth/AuthenticationTokens.yml

https://jira.aminocom.com/browse/BPLAT-12628

BPLAT-12628 Add user_flags attr in  AuthenticationToken entity

---

rest/endpoints/config/users.yml

https://jira.aminocom.com/browse/BPLAT-12627

BPLAT-12627 Add api doc for put/delete user flags

---

rest/endpoints/enriched_metadata/programs.yml
rest/endpoints/recommendations/recommendations.yml
rest/endpoints/schedule/broadcast_slots.yml
rest/endpoints/user_recordings/profile_recordings.yml
rest/snippets/Epg/BroadcastSlotEntity.yml
rest/snippets/Schedule/BroadcastSlotEntity.yml

https://jira.aminocom.com/browse/BPLAT-10388
preview:
- https://confluence.aminocom.com/display/BPLAT/%5BWIP+-+Garrick%5D+API+draft+1#/BroadcastSlots/GetBroadcastSlotsIndex
- https://confluence.aminocom.com/display/BPLAT/%5BWIP+-+Garrick%5D+API+draft#/Recording%20Groups/getRecordingsForGroup

BPLAT-10388 get broadcast slots

---

rest/endpoints/config/users.yml
rest/endpoints/license/management_license.yml
rest/endpoints/user_configuration/user_info.yml
rest/snippets/Config/LicenseEntity.yml

https://jira.aminocom.com/browse/BPLAT-12622

phi/BPLAT-12622: Doc for license management api

---

rest/endpoints/schedule/broadcast_slots.yml

https://jira.aminocom.com/browse/BPLAT-12969

BPLAT-12969: added 404 to API spec

---

rest/endpoints/license/user_licenses_v4.yml
rest/snippets/Config/LicenseEntity.yml

https://jira.aminocom.com/browse/BPLAT-12621
preview: https://confluence.aminocom.com/display/BPLAT/%5BWIP+-+Garrick%5D+API+draft

License v4: create license

---

rest/endpoints/config/users.yml

https://jira.aminocom.com/browse/BPLAT-12627

BPLAT-12627 Fix user flags endpoint specs

---

rest/endpoints/config/users.yml

https://jira.aminocom.com/browse/BPLAT-12627

BPLAT-12627 Add 'Available since' in user_flags endpoint specs

---

rest/endpoints/config/users.yml

https://jira.aminocom.com/browse/BPLAT-12627

BPLAT-12627 Change user_flags add endpoint back to PUT

---

rest/endpoints/license/management_license.yml

https://jira.aminocom.com/browse/BPLAT-13092

BPLAT-13092: Update License management API to v4

---

rest/endpoints/media/live_playable_stream.yml
rest/endpoints/media/recording_playable_stream.yml

https://jira.aminocom.com/browse/BPLAT-12992

BPLAT-12992: Add DRM system parameter and missing streamType parameter for Stream APIs

---

rest/endpoints/user_configuration/user_profiles.yml

https://jira.aminocom.com/browse/BPLAT-13147

BPLAT-13147: Update API documentation for POST

---

rest/endpoints/media/catchup_playable_stream.yml

https://jira.24i.com/browse/BPLAT-13214

phi/BPLAT-13241: API document for new catchup stream api

---

rest/snippets/Media/MediaPlaySession.yml

https://jira.24i.com/browse/BPLAT-13167

phi/BPLAT-13167: update IP field to be nullable

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.aminocom.com/browse/BPLAT-12930

Update new pagination format

---

rest/endpoints/enriched_metadata/genres.yml
rest/endpoints/enriched_metadata/programs.yml
rest/endpoints/enriched_metadata/series.yml

https://jira.aminocom.com/browse/BPLAT-12930

Update new pagination format for meta apis

---

rest/endpoints/enriched_metadata/genres.yml

https://confluence.aminocom.com/display/MAPI/Metadata%3A+Genres

Fix for indent

---

rest/snippets/Media/StreamEntity.yml

https://jira.24i.com/browse/BPLAT-13495

BPLAT-13495: Correct supported protection_types

---

rest/snippets/Media/StreamEntity.yml

https://jira.24i.com/browse/BPLAT-11379

BPLAT-11379 Remove profile_name from list of mandatory attributes for StreamEntity

---

rest/snippets/Media/StreamEntity.yml

https://jira.aminocom.com/browse/BPLAT-13580

[WS] BPLAT-13580 Make StreamProfile attributes non-mandatory

---

rest/endpoints/media/recording_playable_stream.yml

https://jira.24i.com/browse/BCUS-2638

BCUS-2638 Add 404 for /recordings/{recording_id}/relationships/streams

---

rest/endpoints/media/catchup_playable_stream.yml
rest/endpoints/media/live_playable_stream.yml
rest/endpoints/media/recording_playable_stream.yml

https://jira.24i.com/browse/BCUS-2683

BCUS-2683 Update api specs for stream endpoints

---

rest/endpoints/media/media_playback_sessions.yaml

https://jira.aminocom.com/browse/BPLAT-13868

BPLAT-13868: Add user ID to all media play session paths

---

rest/endpoints/media/media_playback_sessions.yaml

https://jira.aminocom.com/browse/BPLAT-12868

BPLAT-12868: Remove obsolete error messages

---

rest/endpoints/user_recordings/profile_recordings.yml

GET recording by broadcast slot ID
https://jira.24i.com/browse/BPLAT-14510

BPLAT-14510: GET recording by broadcast slot ID

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.24i.com/browse/BPLAT-14725

phi/BPLAT-14725: Add filter starts_before to search recordings endpoint

---

rest/endpoints/user_recordings/profile_recordings.yml

Added language parameter to most_popular Recording V4
https://jira.24i.com/browse/BPLAT-13195

naveen.BPLAT-13195: Added language parameter to most_popular Recording V4

---

rest/snippets/EnrichedMetadata/ProgramEntity.yml

https://jira.24i.com/browse/BPLAT-14650

BPLAT-14650: make external_program_id nullable

---

rest/snippets/Media/StreamEntity.yml

https://jira.24i.com/browse/BPLAT-15105

Add ezdrm protection type

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.24i.com/browse/BPLAT-15382

Fix batch delete recordings error code and message

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.24i.com/browse/BCUS-3353

Clarify page number parameter

---

rest/snippets/UserRecordings/AutoRecordingRequestEntity.yml

https://jira.24i.com/browse/BPLAT-14334

Support multi-channel auto-recording

---

rest/endpoints/enriched_metadata/programs.yml

Allow including Program resources in EPG v4
https://jira.24i.com/browse/BPLAT-13692

naveen.BPLAT-13692: Allow including Program resources in EPG v4

---

rest/endpoints/enriched_metadata/programs.yml

Reverts booxmedialtd/api-documentation#142

Revert "naveen.BPLAT-13692: Allow including Program resources in EPG v4"

---

rest/endpoints/user_recordings/profile_recordings.yml

https://jira.24i.com/browse/BPLAT-15802

BPLAT-15802: Deprecate recording group contents endpoints

---

rest/endpoints/user_recordings/profile_recordings.yml

Add new quota field to storage_quota endpoint
https://jira.24i.com/browse/BPLAT-16655

BPLAT-16655: Add new quota field to storage_quota endpoint

---

rest/endpoints/media/catchup_playable_stream.yml
rest/endpoints/media/live_playable_stream.yml
rest/endpoints/media/recording_playable_stream.yml

https://jira.24i.com/browse/BPLAT-16658

Add device_class parameter to Streams API
